GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTc0ODc1MTEzMiwiZXhwIjoxNzQ4NzUxMTgyfQ.uSStY5HjviOnEeZAMpIdkM_1TbByV-h1Mntn1i-WTQY
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTc0ODc1MTEzMn0.qygpEv222PtbtTfa3DqcfE_05hL7pgSP7J_o8Nqmwz0"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTc0ODc1MTEzMn0.qygpEv222PtbtTfa3DqcfE_05hL7pgSP7J_o8Nqmwz0"

}
###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Kyle"
}